[build]
  publish   = "."
  functions = "netlify/functions"

# 既存の CORS・リダイレクト設定（UI 変更不要で API を呼べるように）
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin  = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200
