[build]
  functions = "netlify/functions"
  publish = "."

# Replicate用Function設定（長時間処理対応）
[functions."generate-coloring-replicate"]
  timeout = 300

[functions."test-replicate"]
  timeout = 30

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# リダイレクト設定
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# キャッシュ設定（生成された画像用）
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"