[build]
  functions = "netlify/functions"
  publish = "."

# 非同期処理用のFunction設定
[functions."start-coloring-job"]
  timeout = 10

[functions."check-coloring-job"]
  timeout = 10

[functions."test-replicate"]
  timeout = 30

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# リダイレクト設定
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# キャッシュ設定（生成された画像用）
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"