[build]
  functions = "netlify/functions"
  publish = "."

# 非同期ジョブ処理用Function設定
[functions."start-dalle-job"]
  timeout = 10

[functions."process-dalle-background"]
  timeout = 900

[functions."check-dalle-job"]
  timeout = 10

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"