[build]
  functions = "netlify/functions"
  publish = "."

# DALL-E 2 img-to-img Background Function設定
[functions."process-dalle2-img2img-background"]
  timeout = 900

# 通常Function設定（10秒タイムアウト）
[functions."process-dalle-unified"]
  timeout = 10

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"