[build]
  functions = "netlify/functions"
  publish = "."

# Function設定は個別に指定
[functions."generate-coloring"]
  timeout = 30

[functions."generate-coloring-bg"]
  timeout = 900

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# リダイレクト設定（必要に応じて）
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  